exp_name: evaluation-mode

dataRoot: ./data
custom_dataRoot: ./custom_data
dataset: arxiv
sentence_encoder: ST
model_type: MLP

state_dict_path: ./state_dicts
log_dir: "./log"

lr: 0.001
epochs: 200
batch_size: 5
weight_decay: 0.001
dropout: 0.3
seed: null
workers: 10
device: 2
eval_only: False