exp_name: evaluation-mode

dataRoot: ./data
custom_dataRoot: ./custom_data
dataset: arxiv
model_type: MLP

sentence_encoder: ST
encoder_path: ./lang_models

state_dict_path: ./state_dicts

lr: 0.001
epochs: 200
batch_count: 1001
batch_size: 5
weight_decay: 0.001
dropout: 0.3
seed: null
num_workers: 10
device: 0
eval_only: False

n_way: 3
n_shot: 3
n_query: 2